### PR TITLE
search for log file tar ball.

### PR DESCRIPTION
**Pull request by yuyiguo**
@amaltaro @ticoann 
Please review.  This code show he steps and queries to find the log file tar ball. It is not straight forward.

### CODE REVIEW

**Comment by ticoann** [comment]
Hi Yuyi, do you have any output examples using this query?

**Comment by yuyiguo** [comment]
No. There is no much data in Mongo to test it.

**Comment by ticoann** [comment]
Hi Yuyi,  I create the wiki for steps in english.
https://github.com/dmwm/WMArchive/wiki/Steps-for-Querying-LogCollect-file-Location

Could you check whether I missed anything for the steps and also could run your script against the db you have in vocms013? That way it would be easy to review and debug.

**Comment by vkuznet** [comment]
Please move this into src/pythonWMArchive/Examples directory.

**Comment by vkuznet** [comment]
Used ideas from this PR to implement logCollect look-up on HDFS, no longer need this PR.

**Pull request closed without merging**
