### PR TITLE
add more cpu performance metrics

### PR DESCRIPTION
**Pull request by ticoann**
related to 
https://github.com/dmwm/WMCore/issues/8192

### CODE REVIEW

**Comment by ticoann** [comment]
@vkuznet, Valentin, please review

**Review by vkuznet — APPROVED** [review]
+1

**Comment by vkuznet** [comment]
@ticoann , what about multicore section? So far it is empty dict.

**Comment by ticoann** [comment]
As far as I know I don't think it passes multicore in fwjr. Also multicore is values related to Threads and Stream. (at least in the code)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L718

But @ericvaandering, Eric would know better.

**Comment by ericvaandering** [comment]
Since CMSSW is putting the threads and streams in the CPU performance section, it seems wise to me to keep it there for us even if we had a placeholder for it elsewhere. Maybe we can even delete the empty dict?

**Pull request merged**
