### PR TITLE
Add WMCMSSWSubprocess metrics to WMArchive schema

### PR DESCRIPTION
**Pull request by vkuznet**
Provide necessary changes to WMArchive schema based on WMCore development in the following tickets:
- https://github.com/dmwm/WMCore/pull/11692
- https://github.com/dmwm/WMCore/issues/11660

### CODE REVIEW

**Comment by amaltaro** [comment]
@vkuznet Valentin, it would be helpful to associate this PR with the relevant WMCore changes. Can you please add it to the initial description?

In addition, once these changes get deployed in WMArchive, will the service be able to deal with both old and new document schema? I am asking for this confirmation because at some point we will have both new and old agents in the system, uploading different WMArchive documents.

**Comment by vkuznet** [comment]
Alan, I said many times that WMArchive schema is not used in WMArchive server Go code. It takes whatever we sent to it, add additional meta-data and send it to MONIT. The WMArchive schema is python based code which we developed for clients which should consult it to produce relevant WMArchive document. In other words it should be used by WMCore/Services/WMArchive/DataMap.py codebase but it relies on its own code to create WMArchive docs.  I just keep it in sync with the rest of the changes.

I updated description of this PR to refer to relevant WMCore issue and PR.

**Review by amaltaro — CHANGES_REQUESTED** [review]
Some of the metrics provided in this PR deviate from the changes merged in WMCore, e.g. systemTime vs sysTime; missing userTime; etc.

**Comment by vkuznet** [comment]
Alan, thanks for catching this, I added `userTime` and fixed `sysTime`.

**Pull request merged**
