### PR TITLE
Enabling Yarn mode

### PR DESCRIPTION
**Pull request by meniluca**
This is a temporary solution until we will enable python 2.7 on all nodes in the cluster. For the moment all pyspark jobs in cluster mode will have to be launched using this script as default Python: /afs/cern.ch/user/l/lmeniche/public/python27

Alas, vocms013 is already using that version, therefore we have to exclude it from the script. This done inside the script.

Another important missing step is iptables. Currently running with the --yarn parameter, the job will fail because of executors that are not able to connect to vocms013. E.g.

```
16/03/15 18:22:33 ERROR yarn.ApplicationMaster: Failed to connect to driver at vocms013.cern.ch:50309, retrying ...
```

When a driver is running outside the cluster, it needs to open random port with all the executors inside the cluster in order to orchestrate the computation. There are basically two solutions: the first one is to use puppet to insert iptables rules accepting everything from each node of the cluster; the second one is to switch off iptables.

### CODE REVIEW

**Comment by vkuznet** [comment]
Luca, I'll merge the changes even though it points to your public area. This is certainly we should fix ASAP but I understand the constraint on a cluster. Regarding iptables. We will not turn off iptables, but I'll accept the patch for puppet configuration with cluster nodes IP addresses. We'll adjust iptables only for analytics cluster nodes though. Please provide list of IPs or better provide puppet config change which we can adopt for vocms013.

**Comment by meniluca** [comment]
Hi Valentin.

We can of course add iptables rules by hand, but it is not the suggested solution since every time we will add/remove nodes in the cluster we need to update the list.  The following command will retrieve the list of nodes currently active in the cluster.

```
 curl "http://p01001532965510.cern.ch:8088/ws/v1/cluster/nodes"
```

However the best thing would be to use puppet. This is an example of how your puppet module looks like.

```
define hg_{machine_hostgroup}::{name of pp file} {

  Firewall {
    require => undef,
  }

  $hadoop_node_names = sort(unique(query_nodes("hostgroup~\"hadoop/aimon/datanode\"", 'ipaddress')))

  #$hadoop_node_names = foreman_hg("hadoop/aimon/datanode")
  ensure_resource(hg_{machine_hostgroup}::{name of pp file}::firewall_wrapper, $hadoop_node_names)
}

define hg_{machine_hostgroup}::{name of pp file}::firewall_wrapper {
  #important to have digit in the name, because rule name is used for ordering
  firewall { "150 accept connections from hadoop node ${title}":
    proto => all,
    action => accept,
    source => $title,
    destination => $::ipaddress
  }
}
```

(Thanks Borja Garrido for the puppet code)

**Comment by vkuznet** [comment]
Luca,
could you please provide more details where this configuration change should be
applied. I'm not puppet savvy and need some guidance where and how to apply
this change.
Thanks,
Valentin.

**Comment by meniluca** [comment]
Sure, I am not an expert too though. The best solution would be if you can point where the puppet module is and I can show you exactly what to do. Anyway you should have your hostgroup (H) and your module (M), so that your "M.pp" file looks like:

```
define hg_H::M {
 [...]
}
```

Then inside the module we should have

```
  Firewall {
    require => undef,
  }

  $hadoop_node_names = sort(unique(query_nodes("hostgroup~\"hadoop/aimon/datanode\"", 'ipaddress')))

  #$hadoop_node_names = foreman_hg("hadoop/aimon/datanode")
  ensure_resource(hg_H::M::firewall_wrapper, $hadoop_node_names)
```

and outside we should append:

```
define hg_H::M::firewall_wrapper {
  #important to have digit in the name, because rule name is used for ordering
  firewall { "150 accept connections from hadoop node ${title}":
    proto => all,
    action => accept,
    source => $title,
    destination => $::ipaddress
  }
}
```

**Comment by vkuznet** [comment]
Luca, honestly I don't know where puppet module is and where those *.pp files
are. What I see is the following:

rpm -qf /usr/bin/puppet
puppet-3.8.4cern2-1.ai6.noarch

rpm -qil puppet-3.8.4cern2-1.ai6.noarch | less
which provides puppet, /user/share/puppet, /etc/puppet/

If I look-up

sudo find {/etc/puppet,/usr/share/puppet,/var/lib/puppet} -name "*.pp"

I have nothing

If I look at /etc
sudo find /etc -name "*.pp"

I find *.pp files over here /etc/selinux/targeted/modules/active/

But they're bzip2 files.

I'll be glad to follow your instructions but I can't, I have no idea where
puppet keep/store configuration. Certainly people from IT should know.

**Comment by meniluca** [comment]
I've found the repo where to push the puppet update. I'll tell you here
when my other PR is ready.
Cheers,
Luca

**Comment by meniluca** [comment]
Here it is
https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocms/merge_requests/1
now we have to wait for another merge there.
Cheers,
Luca

**Comment by vkuznet** [comment]
Hmm, may be it's already merged, I got this:

404
The page you're looking for could not be found.

my understanding that once changes would be in it-puppet it will transparently
propagated to our node.

**Comment by meniluca** [comment]
Yes but someone has to accept my "merge request" over there. It is still pending, I don't understand why you cannot see it. At least in the left side [here](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocms) do you see "Merge Requests 1"? I don't know who has to review it or if I have to put someone as assignee.

**Comment by vkuznet** [comment]
Nope, 
I got a page saying

404 The page you're looking for could not be found.
Make sure the address is correct and that the page hasn't moved.
Please contact your GitLab administrator if you think this is a mistake.

and I tried both Chrome and Firefox.

**Comment by meniluca** [comment]
I see, maybe it's because you are not in the AI group. Uhm, then I'm wondering who would be responsible to accept this push. I see that I can "accept" the merge request myself, however am I allowed to do this? Sorry, it's my first time pushing puppet code in another repo in GitLab. I'll ask first to be sure.

**Comment by meniluca** [comment]
Puppet module updated,
code tested in --yarn mode.

Cheers,
Luca

**Comment by vkuznet** [comment]
Luca, thanks a lot, I merged your changes manually since your branch diverged from current one and I don't you to spend more time than necessary on fixing github branches. The merge came into this PR: https://github.com/dmwm/WMArchive/pull/162 and I'm closing this ticket now.

**Pull request closed without merging**
